---

- name: Gather default and custom facts
  hosts: 'all:!localhost'
  gather_facts: True
  sudo: False

  tasks:
    - name: Check IP address of Ansible Controller
      set_fact:
        ansible_controller: '{{ ansible_env.SSH_CLIENT.split(" ") | first }}'
      when: (ansible_controller is undefined and ansible_connection != "local")
      tags: [ 'ferm', 'tcpwrappers' ]

    - name: Update APT cache early if older than 24h
      apt:
        update_cache: True
        cache_valid_time: '{{ apt_update_cache_early }}'
      when: (apt_update_cache_early is defined and apt_update_cache_early)
      sudo: True

- include: config.yml

- name: Upgrade packages
  hosts: 'all:!localhost'
  sudo: True
  tasks:
    - apt: update_cache="yes" upgrade="dist"

- name: Common configuration for all hosts
  hosts: 'all:!localhost'
  sudo: True
  roles:
    - { role: debops.apt_preferences, tags: apt_preferences }
    - { role: debops.etc_services,    tags: etc_services }
    - { role: debops.auth,            tags: auth }
    - { role: debops.pki,             tags: pki }
    - { role: debops.apt,             tags: apt }
    - { role: debops.ferm,            tags: ferm }
    - { role: debops.ntp,             tags: ntp }
    - { role: debops.sshd,            tags: sshd }
    - { role: debops.console,         tags: console }
    - { role: debops.rsyslog,         tags: rsyslog }
    - { role: debops.tcpwrappers,     tags: tcpwrappers }
    - { role: debops.users,           tags: users }
    - { role: debops.sshkeys,         tags: sshkeys }
    - { role: debops.directories,     tags: directories }
    - { role: ../roles/deploy,        tags: deploy }

- include: homes.yml

- hosts: 'all:!localhost'
  sudo: True
  tasks:
    - name: 'Remove ansible from sudoers'
      lineinfile:
        state: 'absent'
        dest: '/etc/sudoers'
        regexp: '^ansible ALL\='
        validate: 'visudo -cf %s'
