---

- name: Generate and load dynamic variables
  hosts: 'all:!localhost'

  tasks:
    - name: Create tmp directory
      file:
        path: '../tmp'
        state: 'directory'
      delegate_to: 127.0.0.1

    - name: Generate local config
      template:
        src: '../templates/vars.yml.j2'
        dest: '../tmp/vars-{{ ansible_hostname }}.yml'
      delegate_to: 127.0.0.1

    - name: Load local config
      include_vars: '../tmp/vars-{{ ansible_hostname }}.yml'
