---

- include: 'config.yml'

- hosts: '{{ hosts }}'
  sudo: yes

  roles:
    - role: ../roles/deploy-git
      deploy_symlinks:
        - src: 'default'
          dest: 'sites/default'
      deploy_optional_commands:
        - 'drush cc all'
        - 'drush updb'
        - 'drush cc all'
        - 'drush en -y features'
        - 'drush fra'
        - 'drush cc all'
