---

- name: Setup user homes
  hosts: 'all:!localhost'
  sudo: True

  tasks:
    - name: Set permissions to 0700 for admins
      file:
        path: "/home/{{ lamp_users[item].name }}"
        mode: "0700"
      with_items: lamp_admins

    - name: Set chroot homes to root ownership
      file:
        path: "/home/{{ item }}"
        owner: "root"
        group: "root"
        mode: "0755"
      with_items: lamp_sites
